### PR TITLE
support spectactle for KDE

### PR DESCRIPTION
**Pull request by IcyAlmond**
kwin doesn't support wlr-screencopy-unstable-v1 required for grim

### CODE REVIEW

**Comment by tatsumoto-ren** [comment]
Does KDE always run on Wayland? If KDE can run under a Xorg session, then you need to test if xclip is installed.

**Comment by tatsumoto-ren** [comment]
I've moved the check for `xclip` or `wlcopy` to a different place, in case GNOME or KDE can be running under Xorg. Please test if everything is okay.

**Comment by IcyAlmond** [comment]
> Does KDE always run on Wayland?

no it doesn't, perhaps `elif IS_XORG:` could be moved up. I'm not sure if you also want it above `if IS_GNOME:` and whether  you want to match the order with the `case platform.xx` statements though so I'll leave that to you?

> I've moved the check for `xclip` or `wlcopy` to a different place, in case GNOME or KDE can be running under Xorg. Please test if everything is okay.

I've just tested it in plasma X11,wayland and gnome X11. For gnome-screenshot, spectacle and slurp+maim and it all seems to work including the tests for xclip and stuff

**Comment by tatsumoto-ren** [comment]
>perhaps `elif IS_XORG` could be moved up

Spectacle can be used in X11 so we can keep it as is. 

> it all seems to work 

Okay, thank you!

**Pull request merged**
